# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carl Harris
email: hello@carlharr.is
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on campaigning and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carlharris.org" # the base hostname & protocol for your site
twitter_username: carlharr
github_username:  3101carlharris

# Build settings
markdown: kramdown
